name: C++ Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libx11-dev

      - name: Build
        run: make

      - name: Clean Artifacts
        run: make clean

  lint:
    name: Code Style Linting
    runs-on: ubuntu-latest
    continue-on-error: true # Non-bloquant

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cpplint
        run: pip install cpplint

      - name: Run Linter
        run: |
          cpplint --filter=-build/header_guard,-legal/copyright,-whitespace/ending_newline,-whitespace/indent,-whitespace/comments,-runtime/threadsafe_fn,-readability/inheritance,-whitespace/blank_line --recursive src/ include/accessoires/ include/capteurs/ include/comportements/ include/core/ include/interfaces/ include/patterns/